name = "Scylla"
uuid = "24d84680-5a81-11f0-094e-d916aee03220"
authors = ["Freddie Daniels fw.daniels01@gmail.com"]
version = "0.5.1"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[executable]
Scylla = "scripts/run.jl"

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "InteractiveUtils", "Profile"]
